env:
  namespace: central-monitoring
  thanosstoregatewaydns: thanos-store-gateway.central-monitoring.svc.cluster.local:10091
  thanosquerierdns: thanos-qurier-ui.central-monitoring.svc.cluster.local:10902
