apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: alertmanager
  name: alertmanager
  namespace: {{ .Values.env.namespace }}
spec:
  ports:
  - name: "9093"
    port: 9093
    targetPort: 9093
  selector:
    app.kubernetes.io/name: alertmanager
status:
  loadBalancer: {}
