apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: alertmanager
  name: alertmanager
  namespace: {{ .Values.env.namespace }}
spec:
  ports:
  - name: httpalert
    port: {{ .Values.alertmanager.port }}
    targetPort: {{ .Values.alertmanager.targetPort }}
  selector:
    app.kubernetes.io/name: alertmanager
status:
  loadBalancer: {}
