apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: alertmanager
  name: alertmanager
  namespace: {{ .Values.env.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager 
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: alertmanager
    spec:
      volumes:
      - name: alertmanager-claim0
        configMap:
          name: alertconfigmap
      containers:
      - args:
        - --config.file=/etc/alertmanager/config.yaml
        - --storage.path=/alertmanager
        image: {{ .Values.alertmanager.image }}
        name: alertmanager
        ports:
        - containerPort: {{ .Values.alertmanager.containerPort }}
        resources: {}
        volumeMounts:
        - mountPath: /etc/alertmanager/
          name: alertmanager-claim0
      restartPolicy: Always
status: {}
