apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.env.namespace }}
data:
  bucket_config.yaml: |-
      type: S3
      config:
        bucket: demo-bucket
        access_key: minioadmin
        secret_key: minioadmin
        endpoint: 10.53.198.173:9000
        insecure: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertconfigmap
  namespace: {{ .Values.env.namespace }}
data:
  config.yaml: |-
      global:
        resolve_timeout: 5m
        smtp_smarthost: "Commscope-com.mail.protection.outlook.com:25"
        smtp_from: "noreply@commscope.com"
      
      #templates:
      #- '/etc/alertmanager/email.tmpl'
      
      
      route:
        group_by: ['alertname']
        group_wait: 30s
        group_interval: 5m
        #repeat_interval: 10m
        receiver: mail
        routes:
        - match_re:
            service: ^.*$
          receiver: mail
          continue: true
      
        - match_re:
            service: ^(localhost:9100)$
          receiver: mail
          continue: true
      
      
      receivers:
      - name: mail
        email_configs:
        - to: deeraj.vijaya@commscope.com
          require_tls: false
          send_resolved: true
          headers:
            subject: '[Themis Alert]'
          html: |
            Hi ,
            <p>
            <h2>
            You have the following firing alerts:
            </h2>
            <ul>
            {{ range .Alerts }}
            <li>{{.Labels.alertname}} on {{ .Labels.instance }} </li>
            <li>{{ .Annotations.summary }}</li>
            <li>{{ .Annotations.description }}</li>
            <li>***********************************************************************</li>
            {{ end }}
             </ul>
            <p>
      
      inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        #equal: ['alertname', 'cluster', 'service']
        equal: ['alertname']
