apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  bucket_config.yaml: |-
      type: S3
      config:
        bucket: demo-bucket
        access_key: minioadmin
        secret_key: minioadmin
        endpoint: 10.53.198.174:9000
        insecure: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertconfigmap
data:
  config.yaml: |-
      global: 
        resolve_timeout: 5m
        smtp_from: noreply@commscope.com
        smtp_smarthost: "Commscope-com.mail.protection.outlook.com:25"
      inhibit_rules: 
        - 
          equal: 
            - alertname
          source_match: 
            severity: critical
          target_match: 
            severity: warning
      receivers: 
        - 
          email_configs: 
            - 
              headers: 
                subject: "[Themis Alert]{{ template \"email.default.subject\" . }}"
              html: |
                  Hi {{ .GroupLabels.email_to }},
                  <p>
                  <h2>
                  You have the following firing alerts:
                  </h2>
                  <ul>
                  {{ range .Alerts }}
                  <li>{{.Labels.alertname}} on {{ .Labels.instance }} </li>
                  <li>{{ .Annotations.summary }}</li>
                  <li>{{ .Annotations.description }}</li>
                  <li>***********************************************************************</li>
                  {{ end }}
                   </ul>
                  <p>
              require_tls: false
              send_resolved: true
              to: deeraj.vijaya@commscope.com
          name: mail
      route: 
        group_by: 
          - alertname
        group_interval: 5m
        group_wait: 30s
        receiver: mail
        routes: 
          - 
            continue: true
            match_re: 
              service: ^.*$
            receiver: mail
          - 
            continue: true
            match_re: 
              service: "^(localhost:9100)$"
            receiver: mail
