apiVersion: v1
data:
  GF_SECURITY_ADMIN_PASSWORD: foobar
  GF_USERS_ALLOW_SIGN_UP: "false"
kind: ConfigMap
metadata:
  namespace: {{ .Values.env.namespace }}
  labels:
    app.kubernetes.io/name: grafana-grafana-config-monitoring
  name: grafana-grafana-config-monitoring
