apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: {{ .Values.env.namespace }}
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30009
  selector:
    app.kubernetes.io/name: grafana
status:
  loadBalancer: {}
