apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: {{ .Values.env.namespace }}
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: {{ .Values.grafana.port }}
    targetPort: {{  .Values.grafana.targetPort }}
    nodePort: {{ .Values.grafana.nodePort }}
  selector:
    app.kubernetes.io/name: grafana
status:
  loadBalancer: {}
