apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: grafana
  name: grafana
  namespace: {{ .Values.env.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
    spec:
      containers:
      - env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: GF_SECURITY_ADMIN_PASSWORD
              name: grafana-grafana-config-monitoring
        - name: GF_USERS_ALLOW_SIGN_UP
          valueFrom:
            configMapKeyRef:
              key: GF_USERS_ALLOW_SIGN_UP
              name: grafana-grafana-config-monitoring
        image: {{ .Values.grafana.image }}
        name: grafana
        ports:
        - containerPort: {{ .Values.grafana.containerPort }}
        resources: {}
        securityContext:
          runAsUser: 104
        volumeMounts:
        - mountPath: /tmp/lib/grafana
          name: grafana-data
        - mountPath: /etc/grafana/provisioning
          name: grafana-claim1
      restartPolicy: Always
      volumes:
      - name: grafana-data
        hostPath:
          path: {{ .Values.grafana.lib }}
      - name: grafana-claim1
        hostPath:
          path: {{ .Values.grafana.plugin }}
status: {}
