apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ipupdate-api-server
  name: ipupdate-api-server
  namespace: {{ .Values.env.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ipupdate-api-server
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: ipupdate-api-server
    spec:
      containers:
      - name: ipupdate-api-server
        image: {{ .Values.ipfinderserver.image }}
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /opt/apps/
          name: ipupdate-api-server-claim0
      volumes:
      - name: ipupdate-api-server-claim0
        hostPath:
          path: {{ .Values.thanosquerier.clusterip }}
      restartPolicy: Always
status: {}



