apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: thanos-compactor
  name: thanos-compactor
  namespace: {{ .Values.env.namespace }}
spec:
  ports:
  - name: headless
    port: 55555
  selector:
    app.kubernetes.io/name: thanos-compactor
status:
  loadBalancer: {}
