apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: thanos-ruler
  name: thanos-ruler
  namespace: {{ .Values.env.namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.thanosruler.port }} 
    targetPort: {{ .Values.thanosruler.targetPort }}
  selector:
    app.kubernetes.io/name: thanos-ruler
status:
  loadBalancer: {}
