apiVersion: v1
kind: Service
metadata:
  name: thanos-store-gateway
  namespace: {{ .Values.env.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.thanosstoregateway.port }}
      targetPort: {{ .Values.thanosstoregateway.targetPort }}
  selector:
    app.kubernetes.io/name: thanos-store-gateway
status:
  loadBalancer: {}
