apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: thanos-querier-ui
  name: thanos-querier-ui
  namespace: {{ .Values.env.namespace }}
spec:
  ports:
  - name: "10902"
    port: {{ .Values.thanosquerier.port }}
    nodePort: {{ .Values.thanosquerier.nodePort }}
  type: NodePort
  selector:
    app.kubernetes.io/name: thanos-querier-ui
status:
  loadBalancer: {}
