apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: thanos-compactor
  name: thanos-compactor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-compactor
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: thanos-compactor
    spec:
      volumes:
      - name: thanos-compactor-claim0
        configMap:
          name: {{ .Release.Name }}-configmap
      containers:
      - args:
        - compact
        - --log.level=debug
        - --data-dir=/data
        - --objstore.config-file=/etc/thanos/bucket_config.yaml
        - --wait
        image: quay.io/thanos/thanos:v0.18.0
        name: thanos-compactor
        resources: {}
        volumeMounts:
        - mountPath: /etc/thanos/
          name: thanos-compactor-claim0
      restartPolicy: Always
status: {}
