apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: thanos-ruler
  name: thanos-ruler
  namespace: {{ .Values.env.namespace }}
spec:
  ports:
  - name: "10903"
    port: 10903
    targetPort: 10902
  selector:
    app.kubernetes.io/name: thanos-ruler
status:
  loadBalancer: {}
