apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: thanos-querier-ui
  name: thanos-querier-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-querier-ui
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: thanos-querier-ui
    spec:
      containers:
      - args:
        - query
        - --http-address=0.0.0.0:10902
        - --query.replica-label=replica
        - --store=10.193.104.19:30006
        - --store.sd-files=/etc/thanos/file_sd.json
        - --store.sd-interval=1m
        - --store=thanos-store-gateway:10091
        image: quay.io/thanos/thanos:v0.18.0
        name: thanos-querier-ui
        ports:
        - containerPort: 10902
        resources: {}
        volumeMounts:
        - mountPath: /etc/thanos/
          name: thanos-querier-ui-claim0
      restartPolicy: Always
      volumes:
      - name: thanos-querier-ui-claim0
        persistentVolumeClaim:
          claimName: thanos-querier-ui-claim0
status: {}
