apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: thanos-querier-ui
  name: thanos-querier-ui
  namespace: {{ .Values.env.namespace }}
spec:
  ports:
  - name: "10902"
    port: 10902
    nodePort: 30020
  type: NodePort
  selector:
    app.kubernetes.io/name: thanos-querier-ui
status:
  loadBalancer: {}
