apiVersion: v1
kind: Service
metadata:
  name: thanos-store-gateway
  namespace: {{ .Values.env.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 10091
      targetPort: 10091
  selector:
    app.kubernetes.io/name: thanos-store-gateway
status:
  loadBalancer: {}
