apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: thanos-querier-ui
  name: thanos-querier-ui
  namespace: {{ .Values.env.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-querier-ui
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: thanos-querier-ui
    spec:
      containers:
      - args:
        - query
        - --http-address=0.0.0.0:10902
        - --query.replica-label=replica
        #- --store=10.53.198.173:30006
        - --store.sd-files=/etc/thanos/file_sd.json
        - --store.sd-interval=1m
        - --store={{ .Values.env.thanosstoregatewaydns }}
        image: {{ .Values.thanosquerier.image }}
        name: thanos-querier-ui
        ports:
        - containerPort: 10902
        resources: {}
        volumeMounts:
        - mountPath: /etc/thanos/
          name: thanos-querier-ui-claim0
      restartPolicy: Always
      volumes:
      - name: thanos-querier-ui-claim0
        hostPath:
          path: {{ .Values.thanosquerier.clusterip }}
status: {}
